create table public.patient_general (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  created_by uuid not null,
  updated_by uuid null,
  email text null,
  residence_address text null,
  phone text null,
  first_name text not null,
  last_name text not null,
  national_id_number text null,
  date_of_birth date not null,
  emergency_contact_name text null,
  emergency_contact_phone text null,
  emergency_contact_relation text null,
  patient_user_id uuid null,
  version integer not null default 1,
  residence_country_id smallint null,
  residence_city_id bigint null,
  citizenship_country_id smallint null,
  constraint ptients_pkey primary key (id),
  constraint patient_general_umcn_key unique (national_id_number),
  constraint patient_general_citizenship_citizenship_country_id_fkey foreign KEY (citizenship_country_id) references countries (id),
  constraint ptients_created_by_fkey foreign KEY (created_by) references auth.users (id),
  constraint ptients_updated_by_fkey foreign KEY (updated_by) references auth.users (id),
  constraint patient_general_country_id_fkey foreign KEY (residence_country_id) references countries (id),
  constraint patient_general_user_id_fkey foreign KEY (patient_user_id) references auth.users (id),
  constraint patient_general_city_id_fkey foreign KEY (residence_city_id) references cities (id)
) TABLESPACE pg_default;

create trigger on_patient_general_update BEFORE
update on patient_general for EACH row
execute FUNCTION handle_updated_at ();