create table public.cities (
  id bigint generated by default as identity not null,
  name jsonb not null,
  postal_code text not null,
  country_id bigint not null,
  created_at timestamp with time zone not null default now(),
  constraint cities_pkey primary key (id),
  constraint cities_name_country_id_key unique (name, country_id),
  constraint cities_country_id_fkey foreign KEY (country_id) references countries (id)
) TABLESPACE pg_default;