create table public.medical_document_types (
  id bigint generated by default as identity not null,
  type_key text not null,
  name_translations jsonb not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  ai_source_locale text null,
  constraint medical_document_types_pkey primary key (id),
  constraint medical_document_types_type_key_key unique (type_key)
) TABLESPACE pg_default;

create trigger on_medical_document_types_update BEFORE
update on medical_document_types for EACH row
execute FUNCTION handle_updated_at ();