create table "public"."examination_type_categories" (
    "id" bigint generated by default as identity not null,
    "name_translations" jsonb not null,
    "ai_source_locale" text,
    "ai_translation_status" text default 'pending'::text,
    "ai_translation_error" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "created_by" uuid,
    "updated_by" uuid
);

-- Create primary key constraint (required for foreign key references)
CREATE UNIQUE INDEX examination_type_categories_pkey ON public.examination_type_categories USING btree (id);

alter table "public"."examination_type_categories" add constraint "examination_type_categories_pkey" PRIMARY KEY using index "examination_type_categories_pkey";

alter table "public"."examination_type_categories" enable row level security;

-- RLS Policies
create policy "Allow authenticated users to delete examination_type_categories"
  on "public"."examination_type_categories"
  as permissive
  for delete
  to authenticated
  using (true);

create policy "Allow authenticated users to insert examination_type_categories"
  on "public"."examination_type_categories"
  as permissive
  for insert
  to authenticated
  with check (true);

create policy "Allow authenticated users to read examination_type_categories"
  on "public"."examination_type_categories"
  as permissive
  for select
  to authenticated
  using (true);

create policy "Allow authenticated users to update examination_type_categories"
  on "public"."examination_type_categories"
  as permissive
  for update
  to authenticated
  using (true);

create policy "Allow service_role full access on examination_type_categories"
  on "public"."examination_type_categories"
  as permissive
  for all
  to service_role
  using (true);

-- Add comment for documentation
COMMENT ON TABLE "public"."examination_type_categories" IS 'Master list of examination type categories (e.g., laboratory, imaging, consultation, procedure, therapy).';

COMMENT ON COLUMN "public"."examination_type_categories"."name_translations" IS 'JSONB object with translations for the category name, e.g., {"en": "Laboratory", "sr-Latn": "Laboratorija"}.';