-- =============================================================================
-- EXAMINATION TYPES TABLE
-- =============================================================================
-- Stores types of medical examinations that can be performed at the clinic.
-- Supports internationalization via JSONB translation fields.
-- =============================================================================

CREATE TABLE public.examination_types (
  -- Primary key
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Unique identifier key (for referencing in code, reports, etc.)
  type_key TEXT NOT NULL UNIQUE,
  
  -- =========================================================================
  -- TRANSLATABLE FIELDS (JSONB: {"en": "...", "sr-Latn": "...", "ru": "..."})
  -- =========================================================================
  name_translations JSONB NOT NULL,
  description_translations JSONB,
  preparation_instructions_translations JSONB,
  
  -- =========================================================================
  -- CORE EXAMINATION DATA
  -- =========================================================================
  duration_minutes INTEGER NOT NULL CHECK (duration_minutes > 0 AND duration_minutes <= 480),
  base_price NUMERIC(10, 2) CHECK (base_price >= 0),
  
  -- =========================================================================
  -- CATEGORIZATION & DISPLAY
  -- =========================================================================
  category_id bigint null,
  color TEXT,
  sort_order INTEGER DEFAULT 0,
  
  -- =========================================================================
  -- REQUIREMENTS & FLAGS
  -- =========================================================================
  is_active BOOLEAN NOT NULL DEFAULT true,
  requires_referral BOOLEAN NOT NULL DEFAULT false,
  requires_fasting BOOLEAN NOT NULL DEFAULT false,
  requires_appointment BOOLEAN NOT NULL DEFAULT true,
  
  -- =========================================================================
  -- AI TRANSLATION TRACKING
  -- =========================================================================
  ai_source_locale TEXT,
  ai_translation_status TEXT DEFAULT 'pending'
    CHECK (ai_translation_status IN ('pending', 'in_progress', 'completed', 'failed')),
  ai_translation_error TEXT,
  
  -- =========================================================================
  -- AUDIT FIELDS
  -- =========================================================================
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  created_by UUID REFERENCES auth.users(id),
  updated_by UUID REFERENCES auth.users(id),
  version INTEGER NOT NULL DEFAULT 1
);

-- =============================================================================
-- COMMENTS
-- =============================================================================
COMMENT ON TABLE public.examination_types IS 'Master list of examination types with internationalized names and scheduling properties.';
COMMENT ON COLUMN public.examination_types.type_key IS 'Unique machine-readable identifier, e.g., blood_test_complete, mri_brain';
COMMENT ON COLUMN public.examination_types.name_translations IS 'JSONB with translations: {"en": "Blood Test", "sr-Latn": "Analiza krvi", "ru": "Анализ крови"}';
COMMENT ON COLUMN public.examination_types.duration_minutes IS 'Expected duration of the examination in minutes (1-480)';
COMMENT ON COLUMN public.examination_types.base_price IS 'Default price in system currency, can be overridden per insurance/contract';
COMMENT ON COLUMN public.examination_types.category IS 'Grouping category: laboratory, imaging, consultation, procedure, therapy, etc.';
COMMENT ON COLUMN public.examination_types.color IS 'Hex color code for calendar/UI display, e.g., #3B82F6';
COMMENT ON COLUMN public.examination_types.preparation_instructions_translations IS 'Patient instructions before exam: fasting requirements, what to bring, etc.';

-- =============================================================================
-- ROW LEVEL SECURITY
-- =============================================================================
ALTER TABLE examination_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to read examination_types"
  ON examination_types FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow authenticated users to insert examination_types"
  ON examination_types FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Allow authenticated users to update examination_types"
  ON examination_types FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Allow authenticated users to delete examination_types"
  ON examination_types FOR DELETE TO authenticated USING (true);

CREATE POLICY "Allow service_role full access on examination_types"
  ON examination_types FOR ALL TO service_role USING (true);