-- Create the professions table
CREATE TABLE public.professions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_translations jsonb NOT NULL,
  ai_source_locale text NULL,
  ai_translation_status text NULL DEFAULT 'pending'
    CHECK (ai_translation_status IN ('pending', 'in_progress', 'completed', 'failed')),
  ai_translation_error text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Add comments
COMMENT ON TABLE public.professions IS 'Master list of professions with internationalized names.';
COMMENT ON COLUMN public.professions.name_translations IS 'JSONB object with translations, e.g., {"en": "Doctor", "sr-Latn": "Lekar", "ru": "Врач"}.';
COMMENT ON COLUMN public.professions.ai_source_locale IS 'The locale used as source for AI translation.';

-- Enable RLS
ALTER TABLE professions ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Allow authenticated users to read professions"
ON professions FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow authenticated users to insert professions"
ON professions FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Allow authenticated users to update professions"
ON professions FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Allow authenticated users to delete professions"
ON professions FOR DELETE TO authenticated USING (true);

CREATE POLICY "Allow service_role full access"
ON professions FOR ALL TO service_role USING (true);