-- Drop the old table if it exists to avoid conflicts
DROP TABLE IF EXISTS public.mkb_10;

-- Create the new table with a JSONB column for translations
CREATE TABLE public.mkb_10 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code VARCHAR(10) NOT NULL,
  diagnosis_translations JSONB,
  diagnosis_la TEXT,
  CONSTRAINT mkb_10_pkey PRIMARY KEY (id),
  CONSTRAINT mkb_10_code_key UNIQUE (code)
);

-- Add comments for clarity
COMMENT ON TABLE public.mkb_10 IS 'International Classification of Diseases, 10th Revision, with multilingual translations in a JSONB column.';
COMMENT ON COLUMN public.mkb_10.code IS 'The official MKB-10 code (e.g., A01.0).';
COMMENT ON COLUMN public.mkb_10.diagnosis_translations IS 'JSONB object containing translations, e.g., {"en": "Typhoid fever", "sr-Latn": "Tifusna groznica"}.';
COMMENT ON COLUMN public.mkb_10.diagnosis_la IS 'The Latin name of the diagnosis.';

-- Create an index on the code for fast lookups
CREATE INDEX idx_mkb_10_code ON public.mkb_10(code);

-- Enable Row Level Security
ALTER TABLE public.mkb_10 ENABLE ROW LEVEL SECURITY;

-- Define RLS policies
-- Allow access to all authenticated users
CREATE POLICY "Allow access to authenticated users"
ON public.mkb_10
FOR ALL
TO authenticated
USING (true);

-- Allow full access to service_role (for admin operations and server-side functions)
CREATE POLICY "Allow full access for service_role"
ON public.mkb_10
FOR ALL
TO service_role
USING (true);