create table public.mkb_10 (
  id bigint generated by default as identity not null,
  number integer null,
  group_num integer null,
  group_name character varying null,
  code_length smallint null,
  code character varying null,
  diagnosis_sr character varying null,
  diagnosis_lat character varying null,
  constraint mkb_10_pkey primary key (id),
  constraint mkb_10_code_key unique (code)
) TABLESPACE pg_default;