-- Stores companies/organizations that patients work for
-- Used for patient as an employer normalization and potential discount programs
CREATE TABLE public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Company name (proper noun, not translated)
    name TEXT NOT NULL,
    
    -- Business identifiers
    tin VARCHAR(50),                -- Tax ID (PIB in Serbia)
    vat VARCHAR(50),                -- VAT number (PDV in Serbia)
    registration_number VARCHAR(50), -- Company registration number
    
    -- Contact information
    address TEXT,
    city_id BIGINT REFERENCES cities(id),
    country_id SMALLINT REFERENCES countries(id),
    phone VARCHAR(50),
    email VARCHAR(255),
    website VARCHAR(255),
    
    -- Company type and settings
    type TEXT NOT NULL DEFAULT 'company',
    discount_percentage NUMERIC(5,2) DEFAULT 0 
        CHECK (discount_percentage >= 0 AND discount_percentage <= 100),
    is_partner BOOLEAN NOT NULL DEFAULT FALSE,
    
    -- Audit fields
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id),
    updated_by UUID REFERENCES auth.users(id)
);

-- Comments for documentation
COMMENT ON TABLE public.companies IS 'Master list of companies/employers for patient employment tracking and partner discount programs.';
COMMENT ON COLUMN public.companies.tin IS 'Tax Identification Number (PIB in Serbia).';
COMMENT ON COLUMN public.companies.vat IS 'VAT registration number (PDV in Serbia).';
COMMENT ON COLUMN public.companies.type IS 'Type of organization: company, government, ngo, educational, healthcare, other.';
COMMENT ON COLUMN public.companies.discount_percentage IS 'Discount percentage for employees of partner companies (0-100).';
COMMENT ON COLUMN public.companies.is_partner IS 'Whether this company has a partnership agreement with the clinic.';

-- Enable Row Level Security
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Allow access to authenticated users"
ON public.companies
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Allow full access for service_role"
ON public.companies
FOR ALL
TO service_role
USING (true);