-- This script is idempotent and can be run multiple times safely.

-- Drop the view first because it depends on the table
DROP VIEW IF EXISTS public.patient_risk_view;

-- Drop the table to ensure a clean slate before creation
DROP TABLE IF EXISTS public.patient_risk;

-- Create the table
create table public.patient_risk (
  id bigint generated by default as identity not null,
  patient_id bigint not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  created_by uuid not null,
  updated_by uuid null,
  gender text null,
  blood_type text null,
  weight numeric null,
  height numeric null,
  waist_circumference numeric null,
  smoking_status text null,
  alcohol_consumption text null,
  physical_activity_level text null,
  stress_level text null,
  version integer not null default 1,
  constraint patient_risk_pkey primary key (id),
  constraint patient_risk_patient_id_key unique (patient_id),
  constraint patient_risk_patient_id_fkey foreign KEY (patient_id) references patient_general (id),
  constraint patient_risk_created_by_fkey foreign KEY (created_by) references auth.users (id),
  constraint patient_risk_updated_by_fkey foreign KEY (updated_by) references auth.users (id)
) TABLESPACE pg_default;

-- Create the trigger
create trigger on_patient_risk_update BEFORE
update on patient_risk for EACH row
execute FUNCTION handle_updated_at ();

-- Create or replace the view
CREATE OR REPLACE VIEW public.patient_risk_view AS
SELECT
  pr.*, -- Select all columns from the patient_risk table
  
  -- Calculate age based on date_of_birth from the joined table
  EXTRACT(YEAR FROM AGE(pg.date_of_birth))::integer AS age,

  -- Calculate BMI, avoiding division by zero, and rounding to 2 decimal places
  CASE
    WHEN pr.height > 0 AND pr.weight > 0 THEN 
      round((pr.weight / ( (pr.height / 100) * (pr.height / 100) ))::numeric, 2)
    ELSE NULL
  END AS bmi,
  
  -- Calculate Obesity Category based on BMI
  CASE
    WHEN pr.height > 0 AND pr.weight > 0 THEN
     CASE
        WHEN (pr.weight / ( (pr.height / 100) * (pr.height / 100) )) < 18.5 THEN 'UNDERWEIGHT'
        WHEN (pr.weight / ( (pr.height / 100) * (pr.height / 100) )) BETWEEN 18.5 AND 24.9 THEN 'NORMAL'
        WHEN (pr.weight / ( (pr.height / 100) * (pr.height / 100) )) BETWEEN 25.0 AND 29.9 THEN 'OVERWEIGHT'
        WHEN (pr.weight / ( (pr.height / 100) * (pr.height / 100) )) >= 30.0 THEN 'OBESE'
        ELSE NULL
      END
    ELSE NULL
  END AS obesity_status
FROM
  patient_risk pr
-- Join to the patient_general table to access date_of_birth
JOIN 
  patient_general pg ON pr.patient_id = pg.id;