create table public.patient_personal (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  created_by uuid not null,
  updated_by uuid null,
  marital_status text null,
  patient_id bigint not null,
  parent_name text null,
  version integer not null default 1,
  education_level text null,
  employer_name text null,
  employment_status text null,
  living_arrangement text null,
  birth_city_id bigint null,
  birth_country_id smallint null,
  profession_id bigint null,
  constraint patient_personal_pkey primary key (id),
  constraint patient_personal_patient_id_key unique (patient_id),
  constraint patient_personal_birth_country_id_fkey foreign KEY (birth_country_id) references countries (id),
  constraint patient_personal_created_by_fkey foreign KEY (created_by) references auth.users (id),
  constraint patient_personal_patient_id_fkey foreign KEY (patient_id) references patient_general (id),
  constraint patient_personal_profession_id_fkey foreign KEY (profession_id) references professions (id),
  constraint patient_personal_updated_by_fkey foreign KEY (updated_by) references auth.users (id),
  constraint patient_personal_birth_city_id_fkey foreign KEY (birth_city_id) references cities (id)
) TABLESPACE pg_default;

create trigger on_patient_personal_update BEFORE
update on patient_personal for EACH row
execute FUNCTION handle_updated_at ();