import { FullPatientClientModel } from "@/types/client-models";

/**
 * Creates a default, empty data structure for a new patient.
 */
export function createNewPatientData(): FullPatientClientModel {
  return {
    general: {
      id: -1, // Temporary ID
      created_at: "",
      updated_at: "",
      created_by: "",
      updated_by: "",
      first_name: "",
      last_name: "",
      date_of_birth: null,
      email: null,
      phone: null,
      residence_country_id: null,
      residence_city_id: null,
      residence_address: null,
      citizenship_country_id: null,
      national_id_number: null,
      patient_user_id: null,
      emergency_contact_name: null,
      emergency_contact_phone: null,
      emergency_contact_relation: null,
      version: 0,
      // Derived fields for client-side use
      citizenshipCountryIso2: null,
      residenceCountryIso2: null,
      residenceCity: null,
    },
    personal: {
      id: 0,
      patient_id: 0,
      created_at: "",
      updated_at: "",
      created_by: "",
      updated_by: "",
      marital_status: null,
      parent_name: null,
      profession_id: null,
      education_level: null,
      employer_id: null,
      employment_status: null,
      living_arrangement: null,
      version: 0,
      birth_country_id: null,
      birth_city_id: null,
      // Derived fields for client-side use
      birthCity: null,
      birthCountryIso2: null,
      profession: null,
      employer: null,
    },
    risk: {
      id: 0,
      patient_id: 0,
      updated_at: "",
      updated_by: "",
      created_at: "",
      created_by: "",
      gender: null,
      height: null,
      weight: null,
      waist_circumference: null,
      blood_type: null,
      alcohol_consumption: null,
      physical_activity_level: null,
      smoking_status: null,
      stress_level: null,
      age: null,
      bmi: null,
      obesity_status: null,
      version: 0,
    },
    notes: [],
    id_documents: [],
    insurances: [],
  };
}
