-- Create the table for medical document types
CREATE TABLE medical_document_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_key TEXT NOT NULL UNIQUE,
    name_translations JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add comments to the table and columns
COMMENT ON TABLE medical_document_types IS 'Master list of medical document types (e.g., lab analysis, discharge list).';
COMMENT ON COLUMN medical_document_types.type_key IS 'A unique, machine-readable key for the document type.';
COMMENT ON COLUMN medical_document_types.name_translations IS 'JSONB object with translations for the document type name.';

-- Create a trigger to automatically update the updated_at timestamp
DROP TRIGGER IF EXISTS medical_document_types_update ON public.medical_document_types;
CREATE TRIGGER on_medical_document_types_update
  BEFORE UPDATE ON public.medical_document_types
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_updated_at();

-- Enable RLS
ALTER TABLE medical_document_types ENABLE ROW LEVEL SECURITY;

-- Create policies for RLS
-- Allow authenticated users to perform all actions
CREATE POLICY "Allow authenticated users to perform all actions"
ON medical_document_types
FOR ALL
TO authenticated
USING (true);

-- Allow service_role to perform all actions
CREATE POLICY "Allow service_role to perform all actions"
ON medical_document_types
FOR ALL
TO service_role
USING (true);