-- Create the table for medical history events
create table public.patient_medical_history_events (
  id bigint generated by default as identity not null,
  patient_id bigint not null,
  title jsonb not null,
  event_date date not null,
  notes jsonb null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  created_by uuid not null,
  updated_by uuid null,
  version integer not null default 1,
  ai_source_locale text not null,
  ai_translation_status text not null default 'idle'::text,
  ai_translation_error text null,
  constraint medical_history_events_pkey primary key (id),
  constraint medical_history_events_patient_id_fkey foreign KEY (patient_id) references patient_general (id),
  constraint patient_medical_history_events_created_by_fkey foreign KEY (created_by) references auth.users (id),
  constraint patient_medical_history_events_updated_by_fkey foreign KEY (updated_by) references auth.users (id),
  constraint chk_ai_translation_status check (
    (
      ai_translation_status = any (
        array[
          'idle'::text,
          'in_progress'::text,
          'completed'::text,
          'failed'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

-- Add comments to the table and columns
COMMENT ON TABLE patient_medical_history_events IS 'Acts as a container/folder for a specific medical event (e.g., a hospital stay).';
COMMENT ON COLUMN patient_medical_history_events.title IS 'Translatable title of the event (e.g., "Cardiology Consultation").';
COMMENT ON COLUMN patient_medical_history_events.event_date IS 'The primary date associated with the event.';

-- Create indexes for faster queries
CREATE INDEX idx_patient_medical_history_events_patient_id ON patient_medical_history_events(patient_id);

-- Create a trigger to automatically update the updated_at timestamp
CREATE TRIGGER handle_patient_medical_history_event_updated_at
BEFORE UPDATE ON public.patient_medical_history_events
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- Enable RLS
ALTER TABLE patient_medical_history_events ENABLE ROW LEVEL SECURITY;

-- Create policies for RLS
CREATE POLICY "Allow authenticated users to manage events"
ON patient_medical_history_events
FOR ALL
TO authenticated
USING (true); -- Placeholder, will need to be refined based on staff roles

CREATE POLICY "Allow service_role to perform all actions"
ON patient_medical_history_events
FOR ALL
TO service_role
USING (true);