-- Create the table for patient medical documents
CREATE TABLE patient_medical_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES patient_medical_history_events(id),
    document_type_id BIGINT NOT NULL REFERENCES medical_document_types(id),
    document_date DATE NOT NULL,
    notes JSONB,
    file_path TEXT,
    file_name TEXT,
    file_size BIGINT,
    file_type TEXT,
    ai_source_locale TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NULL,
    created_by uuid NOT NULL REFERENCES auth.users (id),
    updated_by uuid NULL REFERENCES auth.users (id)
    version integer not null default 1,
);

-- Add comments to the table and columns
COMMENT ON TABLE patient_medical_documents IS 'Stores individual historical medical documents, grouped by a medical event.';
COMMENT ON COLUMN patient_medical_documents.event_id IS 'Links the document to a specific medical history event.';
COMMENT ON COLUMN patient_medical_documents.title IS 'Translatable title of the specific document (e.g., "Lab Results", "Final Report").';
COMMENT ON COLUMN patient_medical_documents.notes IS 'Translatable summary or notes about the document.';
COMMENT ON COLUMN patient_medical_documents.ai_source_locale IS 'The source locale of the original text for AI translation.';

-- Create indexes for faster queries
CREATE INDEX idx_patient_medical_documents_event_id ON patient_medical_documents(event_id);
CREATE INDEX idx_patient_medical_documents_document_type_id ON patient_medical_documents(document_type_id);

-- Create a trigger to automatically update the updated_at timestamp
CREATE TRIGGER handle_patient_medical_documents_updated_at
BEFORE UPDATE ON public.patient_medical_documents
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- Enable RLS
ALTER TABLE patient_medical_documents ENABLE ROW LEVEL SECURITY;

-- Create policies for RLS
CREATE POLICY "Allow authenticated users to manage documents"
ON patient_medical_documents
FOR ALL
TO authenticated
USING (true); -- Placeholder, will need to be refined based on staff roles

CREATE POLICY "Allow service_role to perform all actions"
ON patient_medical_documents
FOR ALL
TO service_role
USING (true);