-- Create the table for patient medical documents
create table public.patient_medical_documents (
  id bigint generated by default as identity not null,
  event_id bigint not null,
  document_type_id bigint not null,
  document_date date not null,
  notes jsonb null,
  file_path text null,
  file_name text null,
  ai_source_locale text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  created_by uuid not null,
  updated_by uuid null,
  file_size numeric null,
  file_type text null,
  version integer not null default 1,
  ai_translation_status text not null default 'idle'::text,
  ai_translation_error text null,
  constraint patient_medical_documents_pkey primary key (id),
  constraint patient_medical_documents_created_by_fkey foreign KEY (created_by) references auth.users (id),
  constraint patient_medical_documents_document_type_id_fkey foreign KEY (document_type_id) references medical_document_types (id),
  constraint patient_medical_documents_event_id_fkey foreign KEY (event_id) references patient_medical_history_events (id),
  constraint patient_medical_documents_updated_by_fkey foreign KEY (updated_by) references auth.users (id),
  constraint chk_patient_medical_documents_ai_translation_status check (
    (
      ai_translation_status = any (
        array[
          'idle'::text,
          'in_progress'::text,
          'completed'::text,
          'failed'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

-- Add comments to the table and columns
COMMENT ON TABLE patient_medical_documents IS 'Stores individual historical medical documents, grouped by a medical event.';
COMMENT ON COLUMN patient_medical_documents.event_id IS 'Links the document to a specific medical history event.';
COMMENT ON COLUMN patient_medical_documents.notes IS 'Translatable summary or notes about the document.';
COMMENT ON COLUMN patient_medical_documents.ai_source_locale IS 'The source locale of the original text for AI translation.';

-- Create indexes for faster queries
CREATE INDEX idx_patient_medical_documents_event_id ON patient_medical_documents(event_id);
CREATE INDEX idx_patient_medical_documents_document_type_id ON patient_medical_documents(document_type_id);

-- Create a trigger to automatically update the updated_at timestamp
CREATE TRIGGER handle_patient_medical_documents_updated_at
BEFORE UPDATE ON public.patient_medical_documents
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- Enable RLS
ALTER TABLE patient_medical_documents ENABLE ROW LEVEL SECURITY;

-- Create policies for RLS
CREATE POLICY "Allow authenticated users to manage documents"
ON patient_medical_documents
FOR ALL
TO authenticated
USING (true); -- Placeholder, will need to be refined based on staff roles

CREATE POLICY "Allow service_role to perform all actions"
ON patient_medical_documents
FOR ALL
TO service_role
USING (true);