create table public.patient_notes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  created_by uuid not null,
  updated_at timestamp with time zone null,
  updated_by uuid null,
  patient_id bigint not null,
  note jsonb not null,
  version integer not null default 1,
  ai_source_locale text not null default 'en'::text,
  ai_translation_status text not null default 'idle'::text,
  ai_translation_error text null,
  constraint patient_notes_pkey primary key (id),
  constraint patient_notes_created_by_fkey foreign KEY (created_by) references auth.users (id),
  constraint patient_notes_patient_id_fkey foreign KEY (patient_id) references patient_general (id),
  constraint patient_notes_updated_by_fkey foreign KEY (updated_by) references auth.users (id),
  constraint chk_patient_notes_ai_translation_status check (
    (
      ai_translation_status = any (
        array[
          'idle'::text,
          'in_progress'::text,
          'completed'::text,
          'failed'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create trigger on_patient_notes_update BEFORE
update on patient_notes for EACH row
execute FUNCTION handle_updated_at ();