create table public.document_types (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  created_by uuid null,
  updated_by uuid null,
  entity text not null,
  translations jsonb not null,
  constraint document_type_pkey primary key (id),
  constraint document_type_created_by_fkey foreign KEY (created_by) references auth.users (id),
  constraint document_type_updated_by_fkey foreign KEY (updated_by) references auth.users (id)
) TABLESPACE pg_default;
