create table public.patient_id_documents (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  created_by uuid not null,
  updated_by uuid null,
  file_path text null,
  file_name text null,
  file_size numeric null,
  file_type text null,
  document_number text not null,
  document_type bigint not null,
  patient_id bigint not null,
  issue_date date not null,
  expiry_date date not null,
  version integer not null default 1,
  constraint patient_id_documents_pkey primary key (id),
  constraint patient_id_documents_patient_id_document_type_key unique (patient_id, document_type),
  constraint patient_id_documents_created_by_fkey foreign KEY (created_by) references auth.users (id),
  constraint patient_id_documents_updated_by_fkey foreign KEY (updated_by) references auth.users (id),
  constraint patient_id_documents_document_type_fkey foreign KEY (document_type) references document_types (id),
  constraint patient_id_documents_patient_id_fkey foreign KEY (patient_id) references patient_general (id)
) TABLESPACE pg_default;

create trigger on_patient_id_documents_update BEFORE
update on patient_id_documents for EACH row
execute FUNCTION handle_updated_at ();