-- Stores the master list of insurance companies
CREATE TABLE public.insurance_providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- e.g., {"en": "State Health Fund", "sr": "Државни здравствени фонд"}
    name_translations JSONB NOT NULL,
    
    -- e.g., {"address": "...", "phone": "..."}
    contact_info JSONB,
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Stores the specific plans offered by each provider
CREATE TABLE public.insurance_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL REFERENCES public.insurance_providers(id) ON DELETE RESTRICT,
    
    -- e.g., {"en": "Gold Plan", "sr": "Златни План"}
    name_translations JSONB NOT NULL,
    
    -- e.g., {"en": "Full coverage...", "sr": "Пуна покривеност..."}
    description_translations JSONB,

    -- e.g., {"deductible": 500, "coPay": 25}
    coverage_details JSONB,
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Connects a patient to a specific insurance plan and policy
CREATE TABLE public.patient_insurances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INT NOT NULL REFERENCES public.patient_general(id) ON DELETE CASCADE,
    plan_id BIGINT NOT NULL REFERENCES public.insurance_plans(id) ON DELETE RESTRICT,
    
    policy_number TEXT NOT NULL,
    lbo_number TEXT,
    
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    effective_date DATE NOT NULL,
    expiry_date DATE,
    
    -- ADDED: File metadata columns
    file_path TEXT,
    file_name TEXT,
    file_size NUMERIC,
    file_type TEXT,

    -- ADDED: User tracking and versioning
    created_by UUID NOT NULL REFERENCES auth.users(id),
    updated_by UUID REFERENCES auth.users(id),
    version INTEGER NOT NULL DEFAULT 1,
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ADDED: Trigger to automatically update the 'updated_at' timestamp
CREATE TRIGGER handle_patient_insurances_updated_at
BEFORE UPDATE ON public.patient_insurances
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();