
  create table "public"."examination_type_categories" (
    "id" bigint generated by default as identity not null,
    "name_translations" jsonb not null,
    "ai_source_locale" text,
    "ai_translation_status" text default 'pending'::text,
    "ai_translation_error" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "created_by" uuid,
    "updated_by" uuid
      );


alter table "public"."examination_type_categories" enable row level security;

alter table "public"."examination_types" drop column "category";

alter table "public"."examination_types" add column "category_id" bigint;

CREATE UNIQUE INDEX examination_type_categories_pkey ON public.examination_type_categories USING btree (id);

alter table "public"."examination_type_categories" add constraint "examination_type_categories_pkey" PRIMARY KEY using index "examination_type_categories_pkey";

alter table "public"."examination_types" add constraint "examination_types_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.examination_type_categories(id) not valid;

alter table "public"."examination_types" validate constraint "examination_types_category_id_fkey";

grant delete on table "public"."examination_type_categories" to "anon";

grant insert on table "public"."examination_type_categories" to "anon";

grant references on table "public"."examination_type_categories" to "anon";

grant select on table "public"."examination_type_categories" to "anon";

grant trigger on table "public"."examination_type_categories" to "anon";

grant truncate on table "public"."examination_type_categories" to "anon";

grant update on table "public"."examination_type_categories" to "anon";

grant delete on table "public"."examination_type_categories" to "authenticated";

grant insert on table "public"."examination_type_categories" to "authenticated";

grant references on table "public"."examination_type_categories" to "authenticated";

grant select on table "public"."examination_type_categories" to "authenticated";

grant trigger on table "public"."examination_type_categories" to "authenticated";

grant truncate on table "public"."examination_type_categories" to "authenticated";

grant update on table "public"."examination_type_categories" to "authenticated";

grant delete on table "public"."examination_type_categories" to "postgres";

grant insert on table "public"."examination_type_categories" to "postgres";

grant references on table "public"."examination_type_categories" to "postgres";

grant select on table "public"."examination_type_categories" to "postgres";

grant trigger on table "public"."examination_type_categories" to "postgres";

grant truncate on table "public"."examination_type_categories" to "postgres";

grant update on table "public"."examination_type_categories" to "postgres";

grant delete on table "public"."examination_type_categories" to "service_role";

grant insert on table "public"."examination_type_categories" to "service_role";

grant references on table "public"."examination_type_categories" to "service_role";

grant select on table "public"."examination_type_categories" to "service_role";

grant trigger on table "public"."examination_type_categories" to "service_role";

grant truncate on table "public"."examination_type_categories" to "service_role";

grant update on table "public"."examination_type_categories" to "service_role";


  create policy "Allow authenticated users to delete examination_type_categories"
  on "public"."examination_type_categories"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Allow authenticated users to insert examination_type_categories"
  on "public"."examination_type_categories"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Allow authenticated users to read examination_type_categories"
  on "public"."examination_type_categories"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Allow authenticated users to update examination_type_categories"
  on "public"."examination_type_categories"
  as permissive
  for update
  to authenticated
using (true);



  create policy "Allow service_role full access on examination_type_categories"
  on "public"."examination_type_categories"
  as permissive
  for all
  to service_role
using (true);



